name: open_fashion_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #LOGIC
  stacked: ^2.3.8

  #UTILS
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  dots_indicator: ^2.1.0
  carousel_slider: ^4.1.1
  tab_indicator_styler: ^2.0.0
  flutter_credit_card: ^3.0.1
  sliding_sheet: ^0.5.2

  #ROUTING
  auto_route: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.8
  auto_route_generator: ^4.0.0
  json_serializable: ^6.1.5

flutter:
  fonts:
    - family: Handlee
      fonts:
        - asset: fonts/Handlee-Regular.ttf

  uses-material-design: true

  assets:
    - assets/
    - assets/header_onboarding/
    - assets/blog/
    - assets/brands/
    - assets/dress/
    - assets/icons/
    - assets/icons/checkOutIcons/
    - assets/icons/contactUsIcons/
    - assets/icons/headerIcon/
    - assets/icons/paymentSuccessIcons/
    - assets/icons/productIcons/
    - assets/icons/productIcons/
    - assets/icons/smallIcons/
    - assets/icons/socialMediaIcon/
    - assets/new_arrival/
    - assets/profile/
    - assets/rings/
    - assets/tShirt/
    - assets/sweater/
    - assets/bag/
    - assets/sweaterWearing/
