import 'package:flutter/material.dart';
import 'package:open_fashion_app/models/blog_model.dart';
import 'package:open_fashion_app/models/product_model.dart';

final List<BlogModel> blogs = [
  BlogModel(
    id: '1',
    title: '2021 Style Guide: The Biggest Fall Trends',
    description:
        'The excitement of fall fashion is here and I am already loving some of the trend forecasts. You guys know how much I love mixing high and low-end – it’s the best way to get the most bang for your buck while still elevating your wardrobe. The same goes for handbags! And honestly they are probably the best pieces to mix and match. I truly think the key to completing a look is with a great bag and I found so many this year that I wanted to share a round-up of my most worn handbags.',
    image: 'assets/blog/blogOne.png',
  ),
  BlogModel(
    id: '2',
    title: '2022 Style Guide: The Biggest Fall Trends',
    description:
        'The excitement of fall fashion is here and I am already loving some of the trend forecasts. You guys know how much I love mixing high and low-end – it’s the best way to get the most bang for your buck while still elevating your wardrobe. The same goes for handbags! And honestly they are probably the best pieces to mix and match. I truly think the key to completing a look is with a great bag and I found so many this year that I wanted to share a round-up of my most worn handbags.',
    image: 'assets/blog/blogTwo.png',
  ),
  BlogModel(
    id: '3',
    title: '2021 Style Guide: The Biggest Fall Trends',
    description:
        'The excitement of fall fashion is here and I am already loving some of the trend forecasts. You guys know how much I love mixing high and low-end – it’s the best way to get the most bang for your buck while still elevating your wardrobe. The same goes for handbags! And honestly they are probably the best pieces to mix and match. I truly think the key to completing a look is with a great bag and I found so many this year that I wanted to share a round-up of my most worn handbags.',
    image: 'assets/blog/blogThree.png',
  ),
  BlogModel(
    id: '4',
    title: '2021 Style Guide: The Biggest Fall Trends',
    description:
        'The excitement of fall fashion is here and I am already loving some of the trend forecasts. You guys know how much I love mixing high and low-end – it’s the best way to get the most bang for your buck while still elevating your wardrobe. The same goes for handbags! And honestly they are probably the best pieces to mix and match. I truly think the key to completing a look is with a great bag and I found so many this year that I wanted to share a round-up of my most worn handbags.',
    image: 'assets/blog/blogFour.png',
  ),
  BlogModel(
    id: '5',
    title: '2022 Style Guide: The Biggest Fall Trends',
    description:
        'The excitement of fall fashion is here and I am already loving some of the trend forecasts. You guys know how much I love mixing high and low-end – it’s the best way to get the most bang for your buck while still elevating your wardrobe. The same goes for handbags! And honestly they are probably the best pieces to mix and match. I truly think the key to completing a look is with a great bag and I found so many this year that I wanted to share a round-up of my most worn handbags.',
    image: 'assets/blog/blogFive.png',
  ),
  BlogModel(
    id: '6',
    title: '2022 Style Guide: The Biggest Fall Trends',
    description:
        'The excitement of fall fashion is here and I am already loving some of the trend forecasts. You guys know how much I love mixing high and low-end – it’s the best way to get the most bang for your buck while still elevating your wardrobe. The same goes for handbags! And honestly they are probably the best pieces to mix and match. I truly think the key to completing a look is with a great bag and I found so many this year that I wanted to share a round-up of my most worn handbags.',
    image: 'assets/blog/blogSix.png',
  ),
];

final List<ProductModel> products = [
  ProductModel(
    id: '1',
    productName: 'LAMEREI',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/sweater/sweaterOne.png',
    price: '\$${120}',
    ratings: '4.3',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '2',
    productName: 'BOSS',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/sweater/sweaterTwo.png',
    price: '\$${100}',
    ratings: '4.2',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '3',
    productName: 'CARTIER',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/sweater/sweaterFour.png',
    price: '\$${70}',
    ratings: '4.0',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '4',
    productName: 'PRADA',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/sweater/sweaterSix.png',
    price: '\$${40}',
    ratings: '3.6',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '5',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/sweater/sweaterNine.png',
    price: '\$${110}',
    ratings: '4.3',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '6',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressTwo.png',
    price: '\$${150}',
    ratings: '4.2',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '7',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressTwo.png',
    price: '\$${130}',
    ratings: '4.6',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '8',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressThree.png',
    price: '\$${130}',
    ratings: '4.3',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '9',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressFour.png',
    price: '\$${120}',
    ratings: '4.4',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '10',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressFive.png',
    price: '\$${125}',
    ratings: '4.5',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '11',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressSix.png',
    price: '\$${130}',
    ratings: '4.6',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '12',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressSeven.png',
    price: '\$${90}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Apparel',
  ),
  ProductModel(
    id: '13',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/ring/ringOne.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
  ProductModel(
    id: '14',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/ring/ringTwo.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
  ProductModel(
    id: '15',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/ring/ringThree.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
  ProductModel(
    id: '16',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/ring/ringFour.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
  ProductModel(
    id: '17',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagOne.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '18',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagTwo.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '19',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagThree.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '20',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagFour.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '21',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagFive.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '22',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagSix.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '23',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtOne.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '24',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtTwo.jpg',
    price: '\$${40}',
    ratings: '4.2',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '25',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtThree.jpg',
    price: '\$${40}',
    ratings: '4.1',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '26',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtFour.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '27',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtFive.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '28',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtSix.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
];

final List<ProductModel> dress = [
  ProductModel(
    id: '6',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressOne.png',
    price: '\$${150}',
    ratings: '4.2',
    sizes: ['S', 'M', 'L'],
    type: 'Dress',
  ),
  ProductModel(
    id: '7',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressTwo.png',
    price: '\$${130}',
    ratings: '4.6',
    sizes: ['S', 'M', 'L'],
    type: 'Dress',
  ),
  ProductModel(
    id: '8',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressThree.png',
    price: '\$${130}',
    ratings: '4.3',
    sizes: ['S', 'M', 'L'],
    type: 'Dress',
  ),
  ProductModel(
    id: '9',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressFour.png',
    price: '\$${120}',
    ratings: '4.4',
    sizes: ['S', 'M', 'L'],
    type: 'Dress',
  ),
  ProductModel(
    id: '10',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressFive.png',
    price: '\$${125}',
    ratings: '4.5',
    sizes: ['S', 'M', 'L'],
    type: 'Dress',
  ),
  ProductModel(
    id: '11',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressSix.png',
    price: '\$${130}',
    ratings: '4.6',
    sizes: ['S', 'M', 'L'],
    type: 'Dress',
  ),
  ProductModel(
    id: '12',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/dress/dressSeven.png',
    price: '\$${90}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Dress',
  ),
];

final List<ProductModel> tshirts = [
  ProductModel(
    id: '23',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtOne.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '24',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtTwo.jpg',
    price: '\$${40}',
    ratings: '4.2',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '25',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtThree.jpg',
    price: '\$${40}',
    ratings: '4.1',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '26',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtFour.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '27',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtFive.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '28',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtSix.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
  ProductModel(
    id: '24',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/tShirt/tShirtTwo.jpg',
    price: '\$${40}',
    ratings: '4.2',
    sizes: ['S', 'M', 'L'],
    type: 'Tshirt',
  ),
];

final List<ProductModel> accessories = [
  ProductModel(
    id: '17',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagOne.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '18',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagTwo.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '13',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/rings/ringOne.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
  ProductModel(
    id: '14',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/rings/ringTwo.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
  ProductModel(
    id: '19',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagThree.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '20',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagFour.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '21',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagFive.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '15',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/rings/ringThree.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
  ProductModel(
    id: '22',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/bag/bagSix.jpg',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Bag',
  ),
  ProductModel(
    id: '16',
    productName: 'BURBERRY',
    description: 'Recycle Boucle Knit Cardigan Pink',
    productImage: 'assets/rings/ringFour.png',
    price: '\$${40}',
    ratings: '3.9',
    sizes: ['S', 'M', 'L'],
    type: 'Ring',
  ),
];

final List<Color> colors = [
  Colors.black,
  Colors.blue,
  Colors.red,
  Colors.orange,
  Colors.yellow,
];

final List<String> homeBanner = [
  'assets/header_onboarding/first_header.png',
  'assets/header_onboarding/headerTwo.jpg',
  'assets/header_onboarding/headerThree.jpg',
  'assets/header_onboarding/headerFour.jpg',
];

final List<String> homeNewArrival = [
  'assets/new_arrival/newOne.png',
  'assets/new_arrival/newTwo.png',
  'assets/new_arrival/newThree.png',
  'assets/new_arrival/newFour.png',
];
